# SConscript

import os

env = Environment()

# Clang
if env['PLATFORM'] == 'darwin':
    env.Append(CFLAGS = ['-Weverything', '-Werror', '-O3'])

# GCC
if env['PLATFORM'] == 'linux':
    env.Append(CFLAGS = ['-Wall', '-Wextra', '-Wpedantic', '-Werror', '-O3'])

# MSVC
if env['PLATFORM'] == 'win32':
    env.Append(CFLAGS = ['/W4', '/WX', '/Ox'])

# for color terminal output when available
if 'TERM' in os.environ:
    env['ENV']['TERM'] = os.environ['TERM']

env.Program('atoi', ['atoi.c'])
env.Program('bits', ['bits.c'])
env.Program('charhist', ['charhist.c'])
env.Program('chario', ['chario.c'])
env.Program('control', ['control.c'])
env.Program('count_digits_and_space', ['count_digits_and_space.c'])
env.Program('decomment', ['decomment.c'])
env.Program('detab', ['detab.c', 'getline.c'])
env.Program('entab', ['entab.c', 'getline.c'])
env.Program('escape', ['escape.c', 'getline.c'])
env.Program('expand', ['expand.c', 'getline.c'])
env.Program('fold', ['fold.c'])
env.Program('hello', ['hello.c'])
env.Program('limits', ['limits.c'])
env.Program('lines', ['lines.c', 'getline.c'])
env.Program('matcher', ['matcher.c', 'getline.c'])
env.Program('maxline_extern', ['maxline_extern.c'])
env.Program('misc', ['misc.c'])
env.Program('power', ['power.c'])
env.Program('shellsort', ['shellsort.c'])
env.Program('simplecheck', ['simplecheck.c', 'vector.c'])
env.Program('strs_test', ['strs_test.c', 'strs.c'])
env.Program('temperature', ['temperature.c'])
env.Program('wc', ['wc.c'])
env.Program('wlhist', ['wlhist.c'])
env.Program('words', ['words.c'])
